from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from shutil import which

from openbase_coder_cli.paths import PLUGIN_CONSOLE_ASSETS_DIR

from .models import PluginRegistry
from .store import save_console_registry


def _import_statement(var_name: str, module_name: str, export_name: str) -> str:
    if export_name == "default":
        return f'import {var_name} from "{module_name}";'
    return f'import {{ {export_name} as {var_name} }} from "{module_name}";'


def _write_generated_registry(console_src_dir: Path, registry: PluginRegistry) -> None:
    generated_dir = console_src_dir / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)
    target = generated_dir / "pluginRegistry.ts"

    imports: list[str] = []
    page_rows: list[str] = []
    view_rows: list[str] = []

    page_index = 0
    for plugin in sorted(registry.plugins, key=lambda item: item.plugin_id):
        for page in plugin.capabilities.console_pages:
            if page.render != "component":
                continue
            var_name = f"PluginPage_{page_index}"
            page_index += 1
            imports.append(_import_statement(var_name, page.import_module, page.export))
            page_rows.append(
                "  {"
                f" pluginId: {json.dumps(plugin.plugin_id)},"
                f" key: {json.dumps(page.key)},"
                f" title: {json.dumps(page.title)},"
                f" route: {json.dumps(page.route)},"
                f" sidebar: {'true' if page.sidebar else 'false'},"
                f" component: {var_name},"
                " },"
            )

    view_index = 0
    for plugin in sorted(registry.plugins, key=lambda item: item.plugin_id):
        for view in plugin.capabilities.project_views:
            var_name = f"PluginView_{view_index}"
            view_index += 1
            imports.append(_import_statement(var_name, view.import_module, view.export))
            view_rows.append(
                "  {"
                f" pluginId: {json.dumps(plugin.plugin_id)},"
                f" stack: {json.dumps(view.stack)},"
                f" title: {json.dumps(view.title)},"
                f" component: {var_name},"
                " },"
            )

    lines = [
        "/* Auto-generated by openbase-coder plugins sync. */",
        'import type { ComponentType } from "react";',
        "",
        *imports,
        "",
        "export type PluginComponentProps = {",
        "  projectPath?: string;",
        "  stack?: string;",
        "  pluginId: string;",
        "};",
        "",
        "export type PluginProjectViewProps = {",
        "  projectPath: string;",
        "  stack: string;",
        "  pluginId: string;",
        "};",
        "",
        "export type PluginConsolePage = {",
        "  pluginId: string;",
        "  key: string;",
        "  title: string;",
        "  route: string;",
        "  sidebar: boolean;",
        "  component: ComponentType<PluginComponentProps>;",
        "};",
        "",
        "export type PluginProjectView = {",
        "  pluginId: string;",
        "  stack: string;",
        "  title: string;",
        "  component: ComponentType<PluginProjectViewProps>;",
        "};",
        "",
        "export const pluginConsolePages: PluginConsolePage[] = [",
        *page_rows,
        "];",
        "",
        "export const pluginProjectViews: PluginProjectView[] = [",
        *view_rows,
        "];",
        "",
    ]

    target.write_text("\n".join(lines) + "\n")


def _install_console_packages(console_dir: Path, registry: PluginRegistry) -> None:
    npm_bin = which("npm")
    if not npm_bin:
        return

    packages: list[str] = []
    for plugin in registry.plugins:
        if any(
            page.render == "component" for page in plugin.capabilities.console_pages
        ):
            packages.extend(plugin.capabilities.console_npm_packages)

    unique_packages = sorted(set(item for item in packages if item))
    if not unique_packages:
        return

    subprocess.run(
        [npm_bin, "install", "--no-save", "--no-package-lock", *unique_packages],
        cwd=str(console_dir),
        check=True,
    )


def sync_console_integration(
    registry: PluginRegistry, workspace_path: str | None
) -> None:
    _sync_iframe_assets(registry)
    payload = {
        "pages": [
            {
                "plugin_id": plugin.plugin_id,
                "pages": [
                    _console_page_payload(plugin.plugin_id, page)
                    for page in plugin.capabilities.console_pages
                ],
            }
            for plugin in registry.plugins
        ],
        "project_views": [
            {
                "plugin_id": plugin.plugin_id,
                "views": [view.__dict__ for view in plugin.capabilities.project_views],
            }
            for plugin in registry.plugins
        ],
    }
    save_console_registry(payload)

    if not workspace_path:
        return

    console_dir = Path(workspace_path) / "console"
    if not console_dir.is_dir():
        return

    _install_console_packages(console_dir, registry)
    _write_generated_registry(console_dir / "src", registry)


def _console_page_payload(plugin_id: str, page) -> dict:
    payload = page.__dict__.copy()
    if page.render == "iframe":
        payload["iframe_url"] = (
            f"/openbase-plugin-assets/{plugin_id}/{page.key}/{page.entrypoint}"
        )
    return payload


def _sync_iframe_assets(registry: PluginRegistry) -> None:
    PLUGIN_CONSOLE_ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    active_targets: set[Path] = set()

    for plugin in registry.plugins:
        source_root = Path(plugin.source_path)
        for page in plugin.capabilities.console_pages:
            if page.render != "iframe":
                continue
            source = (source_root / page.asset_dir).resolve()
            if not source.is_dir():
                raise FileNotFoundError(
                    f"Console page asset_dir not found for {plugin.plugin_id}/{page.key}: {source}"
                )
            target = PLUGIN_CONSOLE_ASSETS_DIR / plugin.plugin_id / page.key
            active_targets.add(target.resolve())
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(source, target)

    for plugin_dir in PLUGIN_CONSOLE_ASSETS_DIR.iterdir():
        if not plugin_dir.is_dir():
            continue
        for page_dir in plugin_dir.iterdir():
            if page_dir.is_dir() and page_dir.resolve() not in active_targets:
                shutil.rmtree(page_dir)
