"""
URL configuration for openbase_coder_cli_app.
"""

from __future__ import annotations

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from openbase_coder_cli.openbase_coder_cli_app.views import (
    agents_md,
    approval_request_detail,
    approval_requests,
    auth_logout,
    auth_refresh_jwt,
    auth_session,
    boilersync_templates,
    bootstrap_run,
    brain_readiness,
    cartesia_voice_settings,
    devices_list,
    dispatcher_voice_settings,
    git_diff,
    global_reports_projects,
    health_check,
    ios_logs_upload,
    launchctl_ignored_settings,
    launchctl_service_action,
    launchctl_services_list,
    livekit_companion_session,
    livekit_room_token,
    livekit_voice_route,
    livekit_voice_route_exit,
    livekit_voice_route_transfer,
    openbase_restart,
    openbase_service_action,
    openbase_services_list,
    plugin_console_registry,
    plugin_detail,
    plugins_list,
    project_reports,
    project_reports_download,
    project_reports_file,
    project_status,
    recent_projects,
    routine_detail,
    routines_list,
    routines_run_due,
    service_status,
    skill_detail,
    skills_list,
    skills_symlink,
    thread_detail,
    thread_interrupt,
    thread_list,
    thread_start_turn,
    user_play,
    user_say,
    uv_tool_detail,
    uv_tool_executable_help,
    uv_tools_list,
)

router = DefaultRouter()

urlpatterns = [
    path("auth/session/", auth_session, name="auth-session"),
    path("auth/refresh-jwt/", auth_refresh_jwt, name="auth-refresh-jwt"),
    path("auth/logout/", auth_logout, name="auth-logout"),
    path("agents-md/", agents_md, name="agents-md"),
    path("health/", health_check, name="health-check"),
    path("brain-readiness/", brain_readiness, name="brain-readiness"),
    path("diagnostics/ios-logs/", ios_logs_upload, name="ios-logs-upload"),
    path("devices/", devices_list, name="devices-list"),
    path("threads/", thread_list, name="thread-list"),
    path("threads/<str:thread_id>/", thread_detail, name="thread-detail"),
    path(
        "threads/<str:thread_id>/interrupt/",
        thread_interrupt,
        name="thread-interrupt",
    ),
    path("threads/<str:thread_id>/turns/", thread_start_turn, name="thread-start-turn"),
    path("approval-requests/", approval_requests, name="approval-requests"),
    path(
        "approval-requests/<str:request_id>/",
        approval_request_detail,
        name="approval-request-detail",
    ),
    path("routines/", routines_list, name="routines-list"),
    path("routines/run-due/", routines_run_due, name="routines-run-due"),
    path("routines/<str:name>/", routine_detail, name="routine-detail"),
    path("user/say/", user_say, name="user-say"),
    path("user/play/", user_play, name="user-play"),
    path("projects/recent/", recent_projects, name="recent-projects"),
    path("projects/status/", project_status, name="project-status"),
    path("projects/reports/", project_reports, name="project-reports"),
    path(
        "projects/reports/global/",
        global_reports_projects,
        name="global-reports-projects",
    ),
    path(
        "projects/reports/file/",
        project_reports_file,
        name="project-reports-file",
    ),
    path(
        "projects/reports/download/",
        project_reports_download,
        name="project-reports-download",
    ),
    path("skills/", skills_list, name="skills-list"),
    path("skills/symlink/", skills_symlink, name="skills-symlink"),
    path("skills/<path:skill_name>/", skill_detail, name="skill-detail"),
    path("plugins/", plugins_list, name="plugins-list"),
    path(
        "plugins/console-registry/",
        plugin_console_registry,
        name="plugin-console-registry",
    ),
    path("plugins/<str:plugin_id>/", plugin_detail, name="plugin-detail"),
    path("boilersync/templates/", boilersync_templates, name="boilersync-templates"),
    path("tools/uv/", uv_tools_list, name="uv-tools-list"),
    path(
        "tools/uv/<str:tool_name>/executables/<str:executable_name>/help/",
        uv_tool_executable_help,
        name="uv-tool-executable-help",
    ),
    path("tools/uv/<str:tool_name>/", uv_tool_detail, name="uv-tool-detail"),
    path("tools/launchctl/", launchctl_services_list, name="launchctl-services-list"),
    path(
        "settings/launchctl-ignored/",
        launchctl_ignored_settings,
        name="launchctl-ignored-settings",
    ),
    path(
        "settings/openbase-services/",
        openbase_services_list,
        name="openbase-services-list",
    ),
    path(
        "settings/restart/",
        openbase_restart,
        name="openbase-restart",
    ),
    path(
        "settings/openbase-services/<str:service_name>/",
        openbase_service_action,
        name="openbase-service-action",
    ),
    path(
        "settings/cartesia-voices/",
        cartesia_voice_settings,
        name="cartesia-voices",
    ),
    path(
        "settings/dispatcher-voice/",
        dispatcher_voice_settings,
        name="dispatcher-voice",
    ),
    path(
        "tools/launchctl/<str:label>/",
        launchctl_service_action,
        name="launchctl-service-action",
    ),
    path(
        "bootstrap/<str:bootstrapper_name>/",
        bootstrap_run,
        name="bootstrap-run",
    ),
    path("git/diff/", git_diff, name="git-diff"),
    path("status/", service_status, name="service-status"),
    path(
        "livekit-companion-session/",
        livekit_companion_session,
        name="livekit-companion-session",
    ),
    path("livekit-room-token/", livekit_room_token, name="livekit-room-token"),
    path("livekit-voice-route/", livekit_voice_route, name="livekit-voice-route"),
    path(
        "livekit-voice-route/exit/",
        livekit_voice_route_exit,
        name="livekit-voice-route-exit",
    ),
    path(
        "livekit-voice-route/transfer/",
        livekit_voice_route_transfer,
        name="livekit-voice-route-transfer",
    ),
    path("", include(router.urls)),
]
