from pathlib import Path

OPENBASE_BASE_DIR = Path.home() / ".openbase"
OPENBASE_SOUNDS_DIR = OPENBASE_BASE_DIR / "sounds"
OPENBASE_INSTRUCTIONS_DIR = OPENBASE_BASE_DIR / "instructions"
CODEX_HOME_DIR = OPENBASE_BASE_DIR / "codex_home"
CODEX_AGENTS_MD_PATH = CODEX_HOME_DIR / "AGENTS.md"
NORMAL_CODEX_HOME_DIR = Path.home() / ".codex"
NORMAL_CODEX_AGENTS_MD_PATH = NORMAL_CODEX_HOME_DIR / "AGENTS.md"
NORMAL_CODEX_CONFIG_PATH = NORMAL_CODEX_HOME_DIR / "config.toml"
OPENBASE_CLAUDE_CONFIG_DIR = OPENBASE_BASE_DIR / "claude_config"
OPENBASE_CLAUDE_JSON_PATH = OPENBASE_CLAUDE_CONFIG_DIR / ".claude.json"
OPENBASE_CLAUDE_MD_PATH = OPENBASE_CLAUDE_CONFIG_DIR / "CLAUDE.md"
OPENBASE_DIRECT_LIVEKIT_INSTRUCTIONS_PATH = (
    OPENBASE_INSTRUCTIONS_DIR / "VOICE_INSTRUCTIONS.md"
)
OPENBASE_DISPATCHER_INSTRUCTIONS_PATH = (
    OPENBASE_INSTRUCTIONS_DIR / "DISPATCHER_INSTRUCTIONS.md"
)
OPENBASE_SUPER_AGENT_INSTRUCTIONS_PATH = (
    OPENBASE_INSTRUCTIONS_DIR / "SUPER_AGENT_INSTRUCTIONS.md"
)
CODEX_DIRECT_LIVEKIT_INSTRUCTIONS_PATH = OPENBASE_DIRECT_LIVEKIT_INSTRUCTIONS_PATH
CODEX_DISPATCHER_INSTRUCTIONS_PATH = OPENBASE_DISPATCHER_INSTRUCTIONS_PATH
OPENBASE_DISPATCHER_CONFIG_PATH = OPENBASE_BASE_DIR / "dispatcher-config.json"
LEGACY_CODEX_DISPATCHER_CONFIG_PATH = CODEX_HOME_DIR / "dispatcher-config.json"
CODEX_DISPATCHER_CONFIG_PATH = OPENBASE_DISPATCHER_CONFIG_PATH
CODEX_SUPER_AGENT_INSTRUCTIONS_PATH = OPENBASE_SUPER_AGENT_INSTRUCTIONS_PATH
LEGACY_CODEX_DIRECT_LIVEKIT_INSTRUCTIONS_PATH = (
    CODEX_HOME_DIR / "VOICE_INSTRUCTIONS.md"
)
LEGACY_CODEX_DISPATCHER_INSTRUCTIONS_PATH = (
    CODEX_HOME_DIR / "DISPATCHER_INSTRUCTIONS.md"
)
LEGACY_CODEX_SUPER_AGENT_INSTRUCTIONS_PATH = (
    CODEX_HOME_DIR / "SUPER_AGENT_INSTRUCTIONS.md"
)
DEFAULT_WORKSPACE_DIR = OPENBASE_BASE_DIR / "workspace"
INSTALLATION_JSON_PATH = OPENBASE_BASE_DIR / "installation.json"
DEFAULT_ENV_FILE_PATH = OPENBASE_BASE_DIR / ".env"
DEFAULT_LOG_DIR = OPENBASE_BASE_DIR / "logs"
LAUNCHD_WRAPPER_DIR = OPENBASE_BASE_DIR / "launchd"
PLIST_DIR = Path.home() / "Library" / "LaunchAgents"
SYSTEMD_UNIT_DIR = Path.home() / ".config" / "systemd" / "user"
LAUNCHD_DOMAIN = "com.openbase.coder"
AUTH_JSON_PATH = OPENBASE_BASE_DIR / "auth.json"
CONSOLE_SETTINGS_JSON_PATH = OPENBASE_BASE_DIR / "console-settings.json"

PLUGIN_BASE_DIR = OPENBASE_BASE_DIR / "plugins"
PLUGIN_REGISTRY_PATH = PLUGIN_BASE_DIR / "plugins.json"
PLUGIN_REQUIREMENTS_PATH = PLUGIN_BASE_DIR / "plugin_requirements.txt"
PLUGIN_SOURCES_DIR = PLUGIN_BASE_DIR / "sources"
PLUGIN_CONSOLE_REGISTRY_PATH = PLUGIN_BASE_DIR / "console" / "registry.json"
PLUGIN_SKILLS_OWNERSHIP_PATH = PLUGIN_BASE_DIR / "skills_ownership.json"
