# Generated by Django 5.2.6 on 2026-02-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('schedule_type', models.CharField(choices=[('cron', 'Cron Expression'), ('interval', 'Fixed Interval')], default='cron', max_length=10)),
                ('cron_expression', models.CharField(blank=True, default='0 * * * *', max_length=100)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('graph_id', models.CharField(default='coder', max_length=255)),
                ('assistant_id', models.CharField(blank=True, default='', max_length=255)),
                ('prompt', models.TextField(default='')),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('last_run_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='', max_length=20)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CronJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('cronjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='openbase_coder_cli_app.cronjob')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
