# Generated by Django 5.2.6 on 2026-05-07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openbase_coder_cli_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CronJobRun",
        ),
        migrations.DeleteModel(
            name="CronJob",
        ),
    ]
